In [2]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3]) # создание массива
arr

array([1, 2, 3])

In [9]:
arr1 = np.zeros((3, 3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr2 = np.ones((5, 5))
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
arr3 = np.arange(0, 18, 2)
arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
arr2.shape # вывод формы

(5, 5)

In [ ]:
arr2.dtype # вывод типа данных

dtype('float64')

In [ ]:
arr770 = np.eye(4) # создаёт единичную матрицу 
print(f'Значение находящееся на 3 строчке , в 3 столбце: {int(arr770[2, 2])}')

Значение находящееся на 3 строчке , в 3 столбце: 1


In [ ]:
arr9 = np.random.randint(0, 5, (5, 7)) # создаем массив со случайными числами
arr9[2:3, 1:4] # с помощью индексации выводим подмассив

array([[2, 3, 4]])

In [68]:
# создание массивов для поэлементарного сложения и умножения
arrq = np.array([
    [7, 8, 9],
    [3, 4, 2],
    [4, 9, 3]
])

arrw = np.array([
    [3, 7, 1],
    [6, 9, 4],
    [3, 1, 8]
])

In [ ]:
# сложение
arrq + arrw

array([[10, 15, 10],
       [ 9, 13,  6],
       [ 7, 10, 11]])

In [ ]:
# умножение
arrq * arrw

array([[21, 56,  9],
       [18, 36,  8],
       [12,  9, 24]])

In [ ]:
# поиск среднего
arr_sum_mean = (arrq + arrw).mean()
arr_sum_mean.item()

10.11111111111111